### ISSUE TITLE
'More' link is removed at bottom of 'New' and 'Newest' 

### ISSUE THREAD

**Issue by realAzazello** [booleandilemma/hn-blacklist#1]
With the script enabled, the 'More' link is removed at bottom of 'New' and 'Newest' pages: 
![image](https://github.com/user-attachments/assets/533e503f-8aa9-4839-97e7-6dd00fb5ad5b)

Environment: 
- Firefox 115.6.0 ESR
- Tampermonkey v5.1.1
- (have other HN related scripts, but I disabled all til determined it was this one)

**_Does_** work on...
- Browser:  Legacy Firefox
- Greasemonkey v3.1.1

**Comment by booleandilemma** [comment]
Hi, the script is not executed on the New and Newest pages. You can see the pages it runs on here: https://github.com/booleandilemma/hn-blacklist/blob/8c32f2933647cd73f10b2dcda6348601004cdaeb/hn-blacklist.js#L4-L5

**Comment by realAzazello** [comment]
> Hi, the script is not executed on the New and Newest pages.

I'll re-run my tests, try to find out what's going on.
