### ISSUE TITLE
How to block job ads spam?

### ISSUE THREAD

**Issue by nick-s-b** [booleandilemma/hn-blacklist#2]
Hi,
Thank you so much for this script! I've been using it to get rid of so much garbage that gets spammed (worst one being Atlas Obscura and their Wikipedia rewrites). Anyway, was wondering how one could go about getting rid of ads that YC companies promote to front page every day? I'm not interested in those at all and don't want to see them.
Thanks again!

**Comment by booleandilemma** [comment]
Hey, I'm really glad to hear that you like it! Atlas Obscura is an HN favorite 😄 

Do you mean posts like the Relationship Hero one below? I think with a little tweaking it should be possible. I notice the post doesn't have an upvote arrow, so I might be able to use that as a way of filtering it out. I'll update this thread again after I've worked on it, stay tuned.

![ad](https://user-images.githubusercontent.com/66350141/156867102-8143a0d5-1111-46b4-ab86-7db1d7ef8bac.png)

**Comment by nick-s-b** [comment]
Yes, exactly those types of posts! You can't comment or upvote and you can only hide them. And YT starts them off at 4th spot as soon as they're posted. Thank you so much for looking into this!

**Comment by booleandilemma** [comment]
Alright, this is done! You can now filter out articles with specific words in the title. So for blocking these types of job ads, just add `"title:is hiring"` to your blacklist:

```
    const blacklist = new Set(
        [
          "title:is hiring"
        ]
    );
```
That will filter out any titles containing the substring "is hiring". (it's a case-insensitive match)

**Comment by nick-s-b** [comment]
@booleandilemma thank you so much!!! It works perfectly!

**Comment by booleandilemma** [comment]
You're welcome!! 👍
